services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: ${DOCKER_HUB_USERNAME}/rf-test-bot:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy

  bot:
    build: .
    command: python tg_bot.py
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  # 4. Веб-сервер Nginx (принимает трафик 80 и 443)
  nginx:
    image: ${DOCKER_HUB_USERNAME}/rf-test-bot-nginx:${IMAGE_TAG:-latest}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - static_volume:/app/static
    depends_on:
      - web

  # 5. Автоматический выпуск и проверка SSL-сертификатов
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    # Проверка обновлений сертификата каждые 12 часов
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  pg_data:
  static_volume:
