# Generated by Django 6.0.7 on 2026-07-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Никнейм')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специализация')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
