events {
worker_connections 1024;
}

http {
include /etc/nginx/mime.types;
default_type application/octet-stream;

upstream django {
    server web:8000;
}

  server {
    listen 80;
    listen [::]:80;
    server_name _;
    # Локация для проверок Certbot
    location /.well-known/acme-challenge/ {
        root /var/var/www/certbot;
    }

    # Все остальные запросы пока просто сбрасываем или шлем на 80 порт Django
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
  }
}